name: Convert JSON to CSV

on:
  workflow_dispatch:
  
jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert docs/data.json to output.csv
        run: |
          echo "date,week,medical,name,time" > output.csv
          jq -r '
            to_entries[] |
            .value as $v |
            $v.hospitals[] as $h |
            [
              .key,
              ($v.date_week | split(" ") | .[1]),
              $h.medical,
              $h.name,
              $h.time
            ] |
            @csv
          ' docs/data.json >> output.csv

      - name: Upload output.csv as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-csv
          path: output.csv
